#Demo Spring application

trigger:
 branches:
    include:
      - master
pr:
  branches:
    include:
      - master

pool:
  vmImage: ubuntu-latest

stages:
  - stage: 'BuildArtifact'
    displayName: ' Building Artifact'
    jobs:
      - job: 'BuildArtifact'
        displayName: 'Building Artifact'
        steps:
        - task: Maven@3
          inputs:
            mavenPomFile: 'pom.xml'
            goals: 'clean package'
            options: '--no-transfer-progress'
            publishJUnitResults: true
            testResultsFiles: '**/surefire-reports/TEST-*.xml'
            javaHomeOption: 'JDKVersion'
            mavenVersionOption: 'Default'
            mavenAuthenticateFeed: false
            effectivePomSkip: false
            sonarQubeRunAnalysis: false
        - task: CopyFiles@2
          inputs:
            SourceFolder: '$(agent.builddirectory)/s/target'
            Contents: '*.jar'
            TargetFolder: '$(build.artifactstagingdirectory)'
            CleanTargetFolder: true
            OverWrite: true
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: 'drop'
            publishLocation: 'Container'
          displayName: 'Publish Artifact'
          
        - task: CopyFiles@2
          inputs:
            SourceFolder: '$(agent.builddirectory)'
            Contents: '**\cicd\**'
            TargetFolder: '$(build.artifactstagingdirectory)'
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: 'cicd'
            publishLocation: 'Container'
            
  - stage: 'Dockerize'
    displayName: 'Create Docker Image'
    condition: and(succeeded(),ne(variables['Build.Reason'],'PullRequest'))
    jobs:
      - job: 'CreateDockerImage'
        displayName: 'Build and Push Docker Image'
        steps:
        - task: DownloadBuildArtifacts@0
          inputs:
            buildType: 'current'
            downloadType: 'single'
            artifactName: 'drop'
            downloadPath: '$(System.ArtifactsDirectory)'
